SELECT USER
FROM DUAL;
-- SUJIN

-- 게시판 만들기

/*
목록에서 노출될 정보
번호, 제목, 작성자, 작성일, 조회수

등록 시 필요한 정보
제목, 내용, 작성자

상세페이지에서 필요한 정보
번호, 작성자, 제목, 내용, 작성일, 조회수
*/

-- 테이블 생성
CREATE TABLE TBL_BOARD
( NO NUMBER
, WRITER VARCHAR2(20) 
, TITLE VARCHAR2(500)
, CONTENT VARCHAR2(4000)
, CRT_DATE DATE
, HITS NUMBER
, CONSTRAINT NO_PK PRIMARY KEY (NO)
);

-- 시퀀스 생성
CREATE SEQUENCE SEQ_BOARD
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCACHE
;

-- 더미 데이터 생성
INSERT INTO TBL_BOARD(NO, WRITER, TITLE, CONTENT, CRT_DATE, HITS)
VALUES(SEQ_BOARD.NEXTVAL, '홍길동', '첫 번째 게시글입니다.', '첫 번째 게시글의 내용입니다.', SYSDATE, 1);
INSERT INTO TBL_BOARD(NO, WRITER, TITLE, CONTENT, CRT_DATE, HITS)
VALUES(SEQ_BOARD.NEXTVAL, '고길동', '두 번째 게시글입니다.', '두 번째 게시글의 내용입니다.', SYSDATE, 1);
INSERT INTO TBL_BOARD(NO, WRITER, TITLE, CONTENT, CRT_DATE, HITS)
VALUES(SEQ_BOARD.NEXTVAL, '송수진', '세 번째 게시글입니다.', '세 번째 게시글의 내용입니다.', SYSDATE, 1);
INSERT INTO TBL_BOARD(NO, WRITER, TITLE, CONTENT, CRT_DATE, HITS)
VALUES(SEQ_BOARD.NEXTVAL, '김수진', '네 번째 게시글입니다.', '네 번째 게시글의 내용입니다.', SYSDATE, 1);
INSERT INTO TBL_BOARD(NO, WRITER, TITLE, CONTENT, CRT_DATE, HITS)
VALUES(SEQ_BOARD.NEXTVAL, '유재석', '다섯 번째 게시글입니다.', '다섯 번째 게시글의 내용입니다.', SYSDATE, 1);
INSERT INTO TBL_BOARD(NO, WRITER, TITLE, CONTENT, CRT_DATE, HITS)
VALUES(SEQ_BOARD.NEXTVAL, '조세호', '여섯 번째 게시글입니다.', '여섯 번째 게시글의 내용입니다.', SYSDATE, 1);
INSERT INTO TBL_BOARD(NO, WRITER, TITLE, CONTENT, CRT_DATE, HITS)
VALUES(SEQ_BOARD.NEXTVAL, '김종국', '일곱 번째 게시글입니다.', '일곱 번째 게시글의 내용입니다.', SYSDATE, 1);
INSERT INTO TBL_BOARD(NO, WRITER, TITLE, CONTENT, CRT_DATE, HITS)
VALUES(SEQ_BOARD.NEXTVAL, '박지성', '여덟 번째 게시글입니다.', '여덟 번째 게시글의 내용입니다.', SYSDATE, 1);
INSERT INTO TBL_BOARD(NO, WRITER, TITLE, CONTENT, CRT_DATE, HITS)
VALUES(SEQ_BOARD.NEXTVAL, '김연아', '아홉 번째 게시글입니다.', '아홉 번째 게시글의 내용입니다.', SYSDATE, 1);
INSERT INTO TBL_BOARD(NO, WRITER, TITLE, CONTENT, CRT_DATE, HITS)
VALUES(SEQ_BOARD.NEXTVAL, '박명수', '열 번째 게시글입니다.', '열 번째 게시글의 내용입니다.', SYSDATE, 1);
INSERT INTO TBL_BOARD(NO, WRITER, TITLE, CONTENT, CRT_DATE, HITS)
VALUES(SEQ_BOARD.NEXTVAL, '정형돈', '열 한 번째 게시글입니다.', '열 한 번째 게시글의 내용입니다.', SYSDATE, 1);
INSERT INTO TBL_BOARD(NO, WRITER, TITLE, CONTENT, CRT_DATE, HITS)
VALUES(SEQ_BOARD.NEXTVAL, '박주영', '열 두 번째 게시글입니다.', '열 두 번째 게시글의 내용입니다.', SYSDATE, 1);
INSERT INTO TBL_BOARD(NO, WRITER, TITLE, CONTENT, CRT_DATE, HITS)
VALUES(SEQ_BOARD.NEXTVAL, '최보윤', '열 세 번째 게시글입니다.', '열 세 번째 게시글의 내용입니다.', SYSDATE, 1);
INSERT INTO TBL_BOARD(NO, WRITER, TITLE, CONTENT, CRT_DATE, HITS)
VALUES(SEQ_BOARD.NEXTVAL, '황석주', '열 네 번째 게시글입니다.', '열 네 번째 게시글의 내용입니다.', SYSDATE, 1);

COMMIT;

-- 테이블 조회
SELECT *
FROM TBL_BOARD
ORDER BY NO;

-- 전체 리스트 조회
SELECT NO, TITLE, WRITER, CRT_DATE, HITS
FROM
(
    SELECT ROWNUM, DATA.*
    FROM
    (
        SELECT NO, WRITER, TITLE, TO_CHAR(CRT_DATE, 'YYYY-MM-DD HH:MI') AS CRT_DATE, HITS
        FROM TBL_BOARD
        --WHERE TITLE LIKE '%번째%'
        ORDER BY NO DESC
    )DATA
)
--WHERE ROWNUM >= 1 AND ROWNUM <= 5
;

-- 상세 페이지 조회
SELECT NO, WRITER, TITLE, CONTENT, CRT_DATE, HITS
FROM TBL_BOARD
WHERE NO = 11;

-- 전체 게시글 수 조회
SELECT COUNT(*)
FROM TBL_BOARD;

-- 게시글 등록
INSERT INTO TBL_BOARD(NO, WRITER, TITLE, CONTENT, CRT_DATE, HITS)
VALUES(SEQ_BOARD.NEXTVAL, '황석주', '열 네 번째 게시글입니다.', '열 네 번째 게시글의 내용입니다.', SYSDATE, 1);

-- 게시글 삭제
DELETE
FROM TBL_BOARD
WHERE NO=16;

-- 게시글 수정
UPDATE TBL_BOARD
SET TITLE = '', CONTENT = '', WRITER = ''
WHERE NO = 14;

-- 게시글 조회시 조회수 올라가기
UPDATE TBL_BOARD
SET HITS = 2
WHERE NO = 19;

------------------------------------------------------------------------------

-- 차트 추가
-- 게시판을 방문하는 방문객을 차트로 표현하기

-- 테이블 생성
CREATE TABLE TBL_VISIT
( VISIT_DATE    VARCHAR2(40)
, VISIT_DIRECT  NUMBER
, VISIT_OTHERS  NUMBER
);

-- 데이터 추가
INSERT INTO TBL_VISIT(VISIT_DATE, VISIT_DIRECT, VISIT_OTHERS)
VALUES('10일', 2, 4);
INSERT INTO TBL_VISIT(VISIT_DATE, VISIT_DIRECT, VISIT_OTHERS)
VALUES('11일', 7, 1);
INSERT INTO TBL_VISIT(VISIT_DATE, VISIT_DIRECT, VISIT_OTHERS)
VALUES('12일', 4, 3);
INSERT INTO TBL_VISIT(VISIT_DATE, VISIT_DIRECT, VISIT_OTHERS)
VALUES('13일', 10, 3);
INSERT INTO TBL_VISIT(VISIT_DATE, VISIT_DIRECT, VISIT_OTHERS)
VALUES('14일', 8, 6);
INSERT INTO TBL_VISIT(VISIT_DATE, VISIT_DIRECT, VISIT_OTHERS)
VALUES('15일', 6, 8);
INSERT INTO TBL_VISIT(VISIT_DATE, VISIT_DIRECT, VISIT_OTHERS)
VALUES('16일', 9, 8);
INSERT INTO TBL_VISIT(VISIT_DATE, VISIT_DIRECT, VISIT_OTHERS)
VALUES('17일', 4, 2);

-- 데이터 확인
SELECT *
FROM TBL_VISIT;